// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// newmark_beta
Rcpp::List newmark_beta(Eigen::Map<Eigen::MatrixXd> dat, Eigen::Map<Eigen::MatrixXd> M, Eigen::Map<Eigen::MatrixXd> C, Eigen::Map<Eigen::MatrixXd> K, double dt, double beta, double gamma);
RcppExport SEXP _resp_newmark_beta(SEXP datSEXP, SEXP MSEXP, SEXP CSEXP, SEXP KSEXP, SEXP dtSEXP, SEXP betaSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type dat(datSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type M(MSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type C(CSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type dt(dtSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(newmark_beta(dat, M, C, K, dt, beta, gamma));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_resp_newmark_beta", (DL_FUNC) &_resp_newmark_beta, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_resp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
