# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Response calculation of S/M-DOF systems using Newmark-beta method
#'
#' @param dat absolute acc. of ground motion
#' @param M,C,K mass/damping/stiff. matrix
#' @param dt time interal (inverse of sampling freq.)
#' @param beta,gamma params of Newmark-beta method.
#' @export
NULL

newmark_beta <- function(dat, M, C, K, dt, beta = 1/4, gamma = 1/2) {
    .Call(`_resp_newmark_beta`, dat, M, C, K, dt, beta, gamma)
}

