# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#'
#'@export
NULL

NewmarkBeta <- function(dat, M, C, K, dt, beta = 1/4, gamma = 1/2) {
    .Call(`_resp_NewmarkBeta`, dat, M, C, K, dt, beta, gamma)
}

#'
#'
#'@export
NULL

NewmarkBeta_NL <- function(dat, w, h, dt, alp, dy_pls, m = 1.0, beta = 0.25, gamma = 0.5) {
    .Call(`_resp_NewmarkBeta_NL`, dat, w, h, dt, alp, dy_pls, m, beta, gamma)
}

